game.sprites = {
  centipedeHead: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png", 
    spriteX: 0,
    spriteY: 0,
    spriteWidth: 40,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 100,
  }),
  centipedeBody: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png", 
    spriteX: 0,
    spriteY: 80,
    spriteWidth: 40,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 100,
  }),
  poisonedMushroom: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png", 
    spriteX: 320,
    spriteY: 0,
    spriteWidth: 40,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 100,
  }),
  regularMushroom: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png", 
    spriteX: 320,
    spriteY: 40,
    spriteWidth: 40,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 100,
  }),
  spider: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png",
    spriteX: 0,
    spriteY: 160,
    spriteWidth: 80,
    spriteHeight: 40,
    numFrames: 8,
    timePerFrame: 100,
    cols: 4,
  }),
  flea: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png",
    spriteX: 320,
    spriteY: 160,
    spriteWidth: 45,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 500,
    cols: 2,
  }),
  scorpion: game.graphics.Sprite({
    sheetSrc: "assets/images/centipede-assets.png",
    spriteX: 0,
    spriteY: 280,
    spriteWidth: 80,
    spriteHeight: 40,
    numFrames: 4,
    timePerFrame: 500,
    cols: 4,
  })
};